### PR TITLE
Import issue

### PR DESCRIPTION
**Pull request by nmoller**
I've cleaned the settings file and corrected the backup/moodle2 (a first iteration to get it working).

### CODE REVIEW

**Comment by mgage** [comment]
When I try to backup and then restore a course I am getting this on at least one course:  
Warning: require(/opt/htdocs/moodle/course/format/site/format.php): failed to open stream: No such file or directory in /opt/htdocs/moodle/course/view.php on line 281

**Comment by mgage** [comment]
When backup (the first time) I get this error:  error/backupatomwhitespacename
When I try to backup again I don't get this error but it appears that the name has been replaced by mathmoodle.

**Comment by nmoller** [comment]
Does the message : "Warning: require(/opt/htdocs/moodle/course/format/site/format.php): failed to open stream: No such file or directory in /opt/htdocs/moodle/course/view.php on line 281" 
happen with a course format the is not present in the restoring instance? If that is the case... that's a feature :) If you dont have it.. it proceeds but a warning is shown.
I'll inspect for the other.

**Comment by mgage** [comment]
That could be the problem.  Here is more information: -- on the other hand I've just saved the instance of the MTH201 course and then tried to restore it.  It looks like the Format name is missing ( or perhaps just the translation) [[pluginname]]

View | Edit | Enrolled users | Delete | Hide | Backup | Restore
Full name
MTH201c Probability
Short name
mth201c
ID number
Category
math
Groupings
0
Groups
0
Role assignments
Enrolment methods
Format
[[pluginname]]
Sections
Modules used

**Comment by nmoller** [comment]
There was some whitespace before timemodified... once arranged the error: error/backupatomwhitespacename gone away.

**Comment by mgage** [comment]
Looks like you were able to fix everything Nelson.  I have been able to backup and restore two large courses successfully.  There are are few minor messages but I'm not sure whether they are actual warnings or just notifications.

**Comment by nmoller** [comment]
Great news Michael! I'll try to finish the backuping process this week. Have a nice weekend.

**Comment by nmoller** [comment]
I'll tested the bckp and everythings seems to be functionnal :) If you have not found other issues we can declare finished that feature. What do you think?

**Pull request merged**
